### ISSUE TITLE
Please add tag for Laravel 5.5 version

### ISSUE THREAD

**Issue by joostvanveen** [Speelpenning-nl/laravel-postcode-nl#16]
Hi Gerben,

Thanks for open sourcing this package. Could you please add a tag on the latest version compatible with Laravel 5.5? I believe that would be commit #6592bc47e06d2d61d80652bec89d48eda40f8260.

We are using this extension in a legacy app still running on Laravel 5.5 LTS. 

As it is now, the only available tags are for Laravel 5.4 (v3.0.3) and Laravel 5.6 (v4.0). Since you updated to L5.6 and later L5.7, which means we cannot require `dev-master` anymore. 

For now, I have forked your package and added the tag myself, but I would be prefer to continue using your version..

**Comment by dejury** [comment]
Same here for me. Please add :)

**Comment by gbs** [comment]
Sorry for being unresponsive. Personal circumstances in the past years kept me from doing maintenance, but I'm back again.

Since support for 5.5 LTS has ended, I decided not to tag v5.5 anymore. You both probably moved to 6 LTS, for which I'll add support.

**Comment by joostvanveen** [comment]
Thanks. We created a forl with 5.5 suppport. We’re now on Laravel 8

**Comment by gbs** [comment]
Hi @joostvanveen,

Updates went all the way to Laravel 8 today. You can use this package again if you like.
