### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by JeroenBoesten** [Speelpenning-nl/laravel-postcode-nl#17]
Hi could you add support for Laravel 5.8? Still love this package.

**Comment by sharkkwak** [comment]
Please add support for Laravel 5.8 @gbs

**Comment by mark-cca** [comment]
And 7.0!

**Comment by gbs** [comment]
Sorry for being unresponsive. Personal circumstances in the past years kept me from doing maintenance, but I'm back again.

For starters, I bumped to 5.8 and tagged it. Now moving to 6 LTS and onwards.

**Comment by gbs** [comment]
Well, we're good to go from 5.8-8.x now.

Sorry for the inconvenience. This being just a ~2.5 hour thing might indicate how dark the clouds were.
