### ISSUE TITLE
Not compatible with Laravel 5.2

### ISSUE THREAD

**Issue by hannenijhuis** [Speelpenning-nl/laravel-postcode-nl#5]
Dear Speelpenning,

I'm trying to use your postcode api service provider in laravel 5.2, but composer says it won't install because you've specified it is compatible with 5.1.x. I could fork and test it on 5.2 if you want?

**Comment by gbs** [comment]
Hello Nijhuis,

I did not had time enough to upgrade my environment to 5.2 until now. At the moment I'm working on the Laravel upgrade and after that I'll start testing my packages.

However, feel free to test if you want ;-)

**Comment by gbs** [comment]
Upgrade finished. Tests are passing.
