### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by dejury** [Speelpenning-nl/laravel-postcode-nl#7]
Can you please make this plugin compatible with Laravel 5.4?

**Comment by gbs** [comment]
I recently wrote Postcode.nl to reactivate my account for the upgrade. I'm waiting for response. I'm also working on throwing an AccountSuspended exception.

**Comment by dejury** [comment]
Okay, great. Please let me know if u can use some help ;)

**Comment by gbs** [comment]
There you go!
