### ISSUE TITLE
Publish config

### ISSUE THREAD

**Issue by markdegrootnl** [Speelpenning-nl/laravel-postcode-nl#9]
Could you call the publishes method in the ServiceProvider to publish your config file?

https://laravel.com/docs/5.4/packages#publishing-file-groups

**Comment by gbs** [comment]
I could, but why would you want to do that? The config options can be set in the .env file.

**Comment by gbs** [comment]
I could, but why would you want to do that? The config options can be set in the .env file.

**Comment by markdegrootnl** [comment]
Sometimes is can be usefull to set some default options for the project instead of using the .env file. Most packages provide a way to publish the config file to allow config overrides.

**Comment by gbs** [comment]
As the key and secret are confidential, I would not want them in the code repository. The only things left are setting a different default timeout and enable the routes by default. Anyway, there you go!
